- README.md
- unity/Assets/Scenes/MCS.unity
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugDiscreteAgentController.cs
- unity/Assets/Scripts/MachineCommonSenseController.cs
- unity/Assets/Scripts/MachineCommonSenseController.cs.meta
- unity/Assets/Scripts/MachineCommonSenseMain.cs
- unity/Assets/Scripts/MachineCommonSensePerformerManager.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/SimObjPhysics.cs
- unity/Assets/Scripts/SimObjType.cs
Updates for ticket MCS-17:
- MCS dynamically generated physics objects are now AI2-THOR `SimObjPhys` objects.  (See `MachineCommonSenseMain.AssignProperties`)
- Created the `MachineCommonSenseController` to replace the AI2-THOR `PhysicsRemoteFPSAgentController`.
- Replaced the old physics simulation behavior from `MachineCommonSenseMain.Update` with calls to `Physics.Simulate` in `MachineCommonSenseController.ProcessControlCommand`.
Other updates:
- Moved custom `Initialize` behavior from `MachineCommonSensePerformerManager` to `MachineCommonSenseController`.
- Added call to `Initialize` in `DebugDiscreteAgentController`.
- Added changes and workflows to our README file.
> MCS-17 Fixed pausing the physics simulation between player steps.

- README.md
- unity/Assets/Scenes/MCS.unity
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugDiscreteAgentController.cs
- unity/Assets/Scripts/MachineCommonSenseController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- Overriding RotateLook in order to allow for relative inputs for rotation/horizon
- Adding error handling for when an input for horizon is greater than 90 or less than -90 degrees
- Updated DebugDiscreteAgentController with debug code for RotateLook when "R" key is pressed
Associated Python API changes here: 
https://github.com/NextCenturyCorporation/MCS/pull/8
> MCS-21 - Override RotateLook

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/MachineCommonSenseController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- Adding lastActionStatus to MetadataWrapper and BaseFPSAgentController
- Setting appropriate lastActionStatus throughout moveInDirection
- Adding generic FAILED action status for all failure cases not covered in the Preliminary Python API doc
Associated Python API changes here: https://github.com/NextCenturyCorporation/MCS/pull/10
> MCS-57 - Add lastActionStatus for Move Actions

- README.md
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugDiscreteAgentController.cs
- unity/Assets/Scripts/MachineCommonSenseController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
MCS-52 and MCS-74
Return new properties in the object metadata output: direction/heading from the player to the object, the array of 3D points that make the object's shape, and whether the object is visible in the camera view.
MCS-87
Accept an objectDirection/receptacleObjectDirection in the action data and use the raycaster to convert it to an objectId, if possible.
> MCS-52 MCS-74 MCS-87

- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/CanOpen_Object.cs
- unity/Assets/Scripts/MachineCommonSenseController.cs
- unity/Assets/Scripts/MachineCommonSenseMain.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- Added lastActionStatus output to OpenObject and CloseObject actions.
- Fixed CanOpen_Object script to work with open and close percentages.
- Created wrapper OpenObject and CloseObject functions due to odd bugs in the Python library.
- Also added lastActionStatus output to all Rotate and Look actions, since I noticed they weren't there.
> MCS-64 MCS-65

- .gitignore
- README.md
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/MachineCommonSenseController.cs
- unity/Assets/Scripts/MachineCommonSenseMain.cs
- unity/Assets/Scripts/MachineCommonSensePerformerManager.cs
Used with Python branch MCS-108 (PR: https://github.com/NextCenturyCorporation/MCS/pull/35)
Previously, physics was simulated (unpaused, then paused again) in the MCS scripts, then images were recorded in AgentManager.EmitFrame, saved as byte arrays to the WWWForm, and sent to the Python API.
Now, physics is simulated in 5 smaller "loops", and images are recorded after each individual loop, snapshoting objects moving slowly as they are affected by the physics simulation.  This should fix the "jerkiness" issue.  Images are no longer recorded in AgentManager.EmitFrame.
To do this without modifying the AI2-THOR Python API itself, I'm hijacking the existing MultiAgentMetadata object.  We're pretending to have multiple agents and using each agent's image output to return one of the images from …
> MCS-108 Unity App: Each action step will now return multiple images.

- unity/Assets/Scripts/MachineCommonSenseController.cs
- unity/Assets/Scripts/MachineCommonSenseMain.cs
- Changed the `moves` object config option to move the object slowly on each substep, so it looks like the object is moving slowly if we take a snapshot of the scene after each substep.  This is helpful if you have an object like a wall that ignores the physics simulation (so you can't just use `forces` on it) but need it to move sometimes.
- Added the `teleports` object config option for any movement that should NOT happen across multiple substeps.
> Changed the 'moves' object config option and added the 'teleports'

- unity/Assets/Resources/MCS/ai2thor_object_registry.json
- unity/Assets/Resources/MCS/material_registry.json
- unity/Assets/Resources/MCS/mcs_object_registry.json
- unity/Assets/Scripts/MachineCommonSenseMain.cs
Restrict the types of materials that may be configured on objects of specific types in the MCS scenes.
> MCS-160 Material Restrictions

- unity/Assets/Scripts/MachineCommonSenseMain.cs
Fixes the issue that Rajesh found with blocks and other objects not being properly marked as "visible" in the object output metadata.
> MCS-191 All colliders now in SimObjVisible layer.

- README.md
- unity/Assets/Scenes/MCS.unity
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/MachineCommonSenseController.cs
- unity/Assets/Scripts/MachineCommonSenseMain.cs
- Structural objects like walls are now assigned the SimObjPhysics script, so we can use the AI2-THOR code to determine if structural objects are visible (we mark them as kinematic so physics and gravity doesn't affect them).
- Dynamically assign visibility points to walls, so bigger walls automatically have more visibility points.
- Dynamically adjust the size of room walls so the output metadata makes more sense.
- Adjusted properties of room walls in MCS scene, adding the SimObjPhysics script and other required components.
- Return structural object metadata to the Python API.
> MCS-217 Return Structural Object Metadata

- README.md
- unity/Assets/Resources/MCS/mcs_object_registry.json
- unity/Assets/Scripts/Contains.cs
- unity/Assets/Scripts/InstantiatePrefabTest.cs
- unity/Assets/Scripts/MachineCommonSenseController.cs
- unity/Assets/Scripts/MachineCommonSenseMain.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/SimObjType.cs
Goal:  Label blocks as "receptacles" so we can use the PutObject action to put other objects on top of them.
- Rewrote the method that generates receptacle spawn points so it always translates global UP into a local direction (which may be down/left/right/forward/back) instead of just using local UP, in case a block is ever lying on its side.  Rewrote other pieces of code to always use global UP.
- Rewrote multiple pieces of code to calculate the size of box colliders to properly account for all types of scaling.  This includes the base object, its receptacle trigger box object, its receptacle trigger box collider, and sometimes an intermediary object.
- Added a new AI2-THOR secondary property, called "stacking", so that larger objects can be stacked on top of small blocks.  Additionally, …
> MCS-163 Use PutObject Action with Blocks

- unity/Assets/Scripts/MCSController.cs
Fixed an issue in which the output images weren't syncing correctly with the output object metadata.
Before, the first image of the `image_list` for a given step was actually supposed to be the last image of the `image_list` for the previous step.
> MCS-284 Fixed Metadata Sync Bug

- unity/Assets/Scripts/MCSMain.cs
Bug fixes:
- Visibility points accidentally positioned inside an object instead of along its side
- Don't add duplicate sets of visibility points to the walls
- Visibility points on dynamic objects (like ramps and occluders) should scale correctly
> Bug fixes to cube dynamically generated visibility points.

- README.md
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Problem:  Held objects, while not active (invisible), still obstruct the raycasting that determines whether an object is visible in the metadata (i.e. the invisible held block hides the cup on the ground).
Solution:  Switch held objects to the AI2-THOR "invisible" layer while held so they are ignored when raycasting to determine object visibility.
> MCS-275 Fix Cup Not Visible

- README.md
- unity/Assets/Scripts/MCSController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/UtilityFunctions.cs
- unity/Assets/Standard Assets/Characters/FirstPersonCharacter/Prefabs/FPSController.prefab
- Ignoring collisions in isObjectColliding (called by DropObject) for ReceptacleTriggerBoxes, since they're not needed and those types of colliders can vary greatly in size
- Hand is now at top level, not camera level for the FPSController, so that the agent hand/objects in the agent's hand stay in front of the agent, and don't start clipping with the agent when rotating the camera towards the floor
> MCS-278 - Fix for DropObject FAILED status

- unity/Assets/Scripts/MCSController.cs
The original ticket was for the reward not being calculated correctly for transferral_goal-0090.json, but the underlying issue was the dropped object fell through the floor, because it was placed under the floor when picked up. This was due to an issue with object scale not being accounted for correctly in this case (thanks for the help @ThomasSchellenbergNextCentury). Retested with transferral_goal-0090 -- looks like goal success registers correctly now. Also tested scale fix with a few other objects (plate/block/box/cup/duck). 
I will leave a note on that ticket as well, in case a separate issue exists with reward calculation so there's no confusion!
> MCS-282 - Fix issues with object scaling

- .gitignore
- README.md
- unity/Assets/ImageSynthesis/ImageSynthesis.cs
- unity/Assets/Scenes/MCS.unity
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/DebugDiscreteAgentController.cs
- unity/Assets/Scripts/MCSController.cs
- unity/Assets/Scripts/MCSMain.cs
Associated MCS changes here: https://github.com/NextCenturyCorporation/MCS/pull/188
Some of the trouble with this ticket was getting the behavior to act the same way within the Unity Editor as it does in the Python API. ~~The only discrepancy left is: within the Unity Editor, running with consistentColors set to true never changes the colors from different runs of a scene, but through the Python API, colors are randomized once at the beginning (but stay consistent during that run). Shouldn't matter too much, but thought it was worth mentioning.~~ (Update: this has been fixed).
> MCS-387 - Option to randomize segmentation mask colors

- unity/Assets/Scripts/MCSController.cs
Fixes the movement bug that Falk reported today on Slack.
We will also need the corresponding Python fix:
https://github.com/NextCenturyCorporation/MCS/pull/193
> MCS-418 Performer should never snap-to-grid.

- unity/Assets/ImageSynthesis/Shaders/Depth.shader
- unity/Assets/Scenes/MCS.unity
(Same description as Python PR)
I've changed the data returned by the Unity depth shader. Previously, the distance from 0 to 25 units was divided among 255 pixels, so each pixel represents about 0.1 unit. Now, I've reduced the far clipping plane to 15 units, and I've split the distance into three sets of 5 units, and each element in the RGB pixel corresponds to one set of 5 units, so each pixel represents about 0.02 unit. This is the best I can do limited to pixel (int) data.
I've tried using the original AI2-THOR code and can't get it to work properly, even after looking at some changes that the AI2-THOR team made after we forked. I'm not convinced that their code works in a way that's useful to us.
Additionally, I can't figure out how to get Unity to return anything other than pixel …
> MCS-346 Changed depth shader to return more depth data. Changed far clipping plane to 15.

- README.md
- unity/Assets/Resources/MCS/primitive_object_registry.json
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/Contains.cs
- unity/Assets/Scripts/InstantiatePrefabTest.cs
- unity/Assets/Scripts/MCSConfig.cs
- unity/Assets/Scripts/MCSController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/SimObjPhysics.cs
- unity/ProjectSettings/ProjectSettings.asset
- Picked-up objects now retain their previous rotation
- Fixed bugs with stacking objects using the PutObject action
- Trying to look up or down too far (past +/- 90 degrees) now does nothing correctly and returns a new CANNOT_ROTATE action status
- Use an object's closest point rather than its center point to decide on whether to return an OBSTRUCTED action status
- Added the NOT_MOVEABLE action status
- Updated the order in which specific action status are returned (NOT_* vs OUT_OF_REACH)
- Set held object colliders to be invisible so held objects won't obstruct visibility to other objects.
- Updated Changelog in README.
> MCS-68 Fixed many little bugs discovered during integration testing

- unity/Assets/Scripts/DebugDiscreteAgentController.cs
- unity/Assets/Scripts/MCSController.cs
The movement restriction on the UNITY side was originally added to fix a bug with moving around while running scenes with the Unity Editor: https://github.com/NextCenturyCorporation/ai2thor/commit/2988a60400a5c9580b5fe301cede237fb054c721
I've simply shifted the restriction from the MCSController to the DebugDiscreteAgentController so it only affects runs with the Unity Editor. Our MCS Python library already adds its own movement restrictions, and those will remain in place until we remove them.
Since this is a minor change, I wasn't sure if we should "get it in" before the big AI2-THOR merge.
> Removed movement restriction in MCS Controller.

- unity/Assets/Resources/MCS/Scenes/wall_materials.json
- unity/Assets/Scripts/MCSMain.cs
Old property still exists for backwards comparability and will be used for any individual wall that is not given a value.
> Updated config to have wall materials for each wall separately. 

- unity/Assets/Scripts/MCSMain.cs
This is a much simplier fix to MCS-619 leaking materials.  After cleaning up all the objects when switching scenes, we delete all unused assets via a unity command.
> MCS-619 Leaking materials - added code to remove unused assets

- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Fixed issue where some containers, when picked up, did not have their contained objects picked up.  This fixes this.
There is a corresponding pull request for integration tests. https://github.com/NextCenturyCorporation/MCS/pull/304
Note: Integration test 46 and 48 will fail until pull request in MCS 303 is merged.  https://github.com/NextCenturyCorporation/MCS/pull/303
> Mcs 473 pickup contained objects

- unity/Assets/ImageSynthesis/ImageSynthesis.cs
Possible fix to issue https://github.com/NextCenturyCorporation/MCS/issues/336
The issue is that the fuse walls are composed of many segments that are overlapping with each other.
Current:
Fixed:
Options include:
- Adding a special case in our Unity code for the fuse walls (i.e. exactly what I've done in this PR). Very hacky, but trivial to implement.
- Update the scene generator to reduce the size of fuse wall segments so they don't overlap. Would require recreating and re-releasing all the instrumental action scenes.
- Dynamically identifying overlapping fuse wall segments and reducing their size in Unity? Would likely either be very complicated or hacky.
I'm open to discussing our options!
EDIT: Adding the RGB image for context:
> Hotfix to issue with showing overlapping fuse walls from agent instrumental action scenes in object instance segmentation masks.

- unity/Assets/Scripts/MCSMain.cs
There was a bug that didn't reset everything the intuitive physics flag set.  Therefore, when some tests were run after intuitive physics was set, it would fail.  The fix was applied in a branch that was put on hold.  This merge cherry-picks that fix to development.  Note: git cherry-pick didn't work for me so i manually copied the changes.  There will be an additional integration test in an upcoming MCS PR.
> cherry picked fix to intuitive physics reset

- unity/Assets/Scripts/Contains.cs
The bug was if chest_1 was switched to pickupable and you tried to pick it up, it would throw an nre. Normally it is a static object but in the case it or any similar static objects like it need this property, this will fix it.
> Picking up static containers when switched to a pickupable object throws nre exception fixed

- unity/Assets/Resources/MCS/Scenes/RAMPS.json
- unity/Assets/Scenes/MCS.unity
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/MCSController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/ProjectSettings/GraphicsSettings.asset
I made a capsule cast method that centers the bottom of the capsule cast by shooting a sphere cast to the floor and picking the highest point it hits rather than getting the min y of the collider. The agents capsule collider now shrinks and expands depending on the pose. I left the debugging gizmos as comments because they are extremely helpful visualizations for any future debugging.
*** 
The agent can ascend ramps at 50 degree angles. This is _**not**_ intentional and buggy and happens every other time it tries to ascend it. When making scenes for eval tests, we should not have any ramps  **46 > x < 59**.
**<= 45** always works the agent will ascend
**>= 60** always prevents the agent from moving as intended
> Fixed Ramps

- unity/Assets/ImageSynthesis/ImageSynthesis.cs
When testing metadata level enums on the python API, I noticed that colors in the segmentation masks were no longer being randomized for level2 metadata. Noticed it was broken in 0.4.3 as well (may have happened in the ai2thor upgrade?) 
Ended up being an easy fix. It may impact the color map ticket as well.
> Fix bug with segmentation masks

- README.md
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Notes:
- Since dropping/throwing/placing devices are also currently tagged as structural objects, returning NOT_OBJECT seemed potentially confusing, which is why I chose NOT_INTERACTABLE instead.
- Returning OUT_OF_REACH is its own bag of worms...
Corresponding Python PR: https://github.com/NextCenturyCorporation/MCS/pull/407
> MCS-889 Trying to Close, Open, or Place using the floor/wall now returns NOT_INTERACTABLE rather than NOT_RECEPTACLE

- unity/Assets/Addressables/MCS/Soccer_Ball/Materials.meta
- unity/Assets/Addressables/MCS/Soccer_Ball/Materials/Black-Ball-Material.mat.meta
- unity/Assets/Addressables/MCS/Soccer_Ball/Materials/White-Ball-Material.mat.meta
- unity/Assets/Addressables/MCS/Soccer_Ball/Meshes.meta
- unity/Assets/Addressables/MCS/Soccer_Ball/Meshes/Soccer Ball Mesh.fbx.meta
- unity/Assets/Addressables/MCS/Soccer_Ball/Prefabs.meta
- unity/Assets/Addressables/MCS/Soccer_Ball/Prefabs/Soccer Ball.prefab.meta
- unity/Assets/Addressables/MCS/Soccer_Ball/Textures.meta
- unity/Assets/Addressables/MCS/Soccer_Ball/Textures/Soccer Ball Normal Map.png.meta
- unity/Assets/Resources/MCS.meta
- Deleted the incorrect soccer ball files from `MCS/Soccer_Ball`
- Moved the correct soccer ball files from `MCS/UnityAssetStore/Soccer_Ball` to `MCS/Soccer_Ball`
- Ensured the old files were no longer part of the addressables group (they must have been removed automatically)
- I'll also remove the old files from the [mcs-private](https://github.com/NextCenturyCorporation/mcs-private/tree/master/UnityAssetStore) repo shortly.
> Moved the soccer ball files properly.

- unity/Assets/Scripts/MCSMain.cs
Small fix to hide the robot's body per discussions in Teams/Slack. Tested pickup/dropping objects within Unity, ran integration tests, and took a look at the depth and segmentation maps -- everything seemed fine. Also checked first frame per Erick's comment in slack to make sure it didn't take a frame to not render the robot (I just took a scene file and updated the rotation so the camera was pointing straight down at start).
> Making robot body invisible (MCS-912).

- unity/Assets/Scripts/MCSMain.cs
Always override floor properties in intuitive physics scenes. Without using the expected friction values, objects don't move correctly (for example, objects that are supposed to exit the scene may not), and they may not be in the correct position when their implausible event occurs.
I've added MCS-570 into the sprint to add integration tests that verify object movement in intuitive physics scenes.
Here's an example scene (change extension from `.txt` to `.json`):
[eval_4_validation_spatio_temporal_continuity_0001_01.txt](https://github.com/NextCenturyCorporation/ai2thor/files/7282261/eval_4_validation_spatio_temporal_continuity_0001_01.txt)
> Fixed a bug with incorrect friction in intuitive physics scenes.

- unity/Assets/Scenes/MCS.unity
Small adjustment to the lighting of the scene, so that we don't use a skybox and instead use a basic color gradient. Reflections will now be independent of the skybox. 
We are using a single reflection probe in the center when the scene starts, so we can get a neutral even lighting to cover all scenes. It only updates on start, so there's no real perf issue. We can update more frequently if we want more accuracy. We can also use reflection probes for objects for which it's relevant.
> MCS-949: Adjusting lighting settings on the scene

- unity/Assets/Scripts/MCSMain.cs
- unity/Assets/Scripts/PhysicsSceneManager.cs
Corresponding [MCS PR](https://github.com/NextCenturyCorporation/MCS/pull/465)
To replicate switch your MCS branch to **MCS-848-Testing-Example**. Run those tests with a build that was **NOT** built from **MCS-848**. Then make a **MCS-848** build and re-run the tests. The bug should be fixed.
This fix just deactivates and activates the agents colliders between scene changes so that SimObjects are placed first then the agents colliders are activated. It seemed like depending on the agents location between scene changes, if the agent was inside where a seesaw would be placed, that one frame would clip the seesaw into the agent and cause it to collide irrationally.
> Seesaws being vertical during integration testing bug fix

- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
It seems like the Push/Pull action wasn't totally fixed either so I edited that based on the conversation in [teams](https://gov.teams.microsoft.us/l/message/19:gcch:959d7221399c4fe08b3ac2def85e1f0d@thread.skype/1642084651235?tenantId=74cf14f4-38e0-460b-9d96-c0a51cb4a55c&groupId=bd0afc79-5b79-4a03-a04a-00fc785501de&parentMessageId=1642021197022&teamName=PIAGET%20(MCS)&channelName=MCS%20Technical&createdTime=1642084651235) making structural objects always say not moveable while non-movable sim objects throw out of reach first then 'not moveable' once you're close enough. 
My reordering the code around solution for Open/Close seemed a little more straight forward than the [ticket ](https://nextcentury.atlassian.net/jira/software/projects/MCS/boards/94?selectedIssue=MCS-499) made it out to …
> Close, Open, and Push object errors thrown reordering

- unity/Assets/Addressables/MCS/Scenes/lava.json
- unity/Assets/Addressables/MCS/Scenes/lava.json.meta
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/MCSController.cs
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/472)
Lava detection is based on the agents collider radius. This means from the agents perspective it is **not** always directly on top of lava when receiving lava haptic feedback. The lava detection radius can be easily adjusted if we want it bigger or smaller. The way haptic feedback is implemented here leaves flexibility for future haptic feedbacks to happen simultaneously.
> Haptic feedback for lava and step output

- unity/Assets/Addressables/MCS/primitive_object_registry.json
- unity/Assets/Scripts/MCSMain.cs
Implemented various improvements to support pushable block tools:
- Added a new cube shape with rounded corners. Helps make pushing smoother.
- Auto generate visibility points for all cubes in interactive scenes. Previously cubes were assigned a limited number of visibility points, which were stretched across the entire cube, even when the cube was scaled up. This made pushing difficult, because the proximity of the nearest visibility point is used to determine if an object is "in reach".
> MCS-1151 Various Block Tool Improvements

- unity/Assets/Scripts/MCSMain.cs
Corresponding Python PR: https://github.com/NextCenturyCorporation/MCS/pull/496
Impulse force will be useful for throwing the soccer ball in the "moving target" task, and possibly other tasks in the future.
> MCS-1160 Added option for impulse force to MCS object config schema (Unity)

- unity/Assets/Scripts/MCSMain.cs
- unity/Assets/Scripts/StructureObject.cs
Since AI2-THOR raycasts from the robot to all nearby visibility points all the time, having lots of visibility points dramatically impacts performance. Since the lip objects are cloned from the platform object, they inherit the platform's visibility points, which were previously scaled for the size of the platform. This PR recreates all the visibility points for the lips to use the appropriate scale. My goal is for each object to have a "reasonable" number of visibility points.
> MCS-1201 Reduced the number of visibility points on platform lip objects to improve runtime performance

- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/MCSMain.cs
If you run this build in human input mode copy the huge_room from Addressables/MCS/Scenes.
I also fixed an issue of not being able to see long distances because the camera clipping plane for max distance was too short.
Try messing around with different values for huge room such as 100x100, 3x100, 100x3, 12x12, 13x16, 15x44, 21x81. Looking at how the lights are placed in the scene view window in the editor for these uses cases which should show you how this behavior works.
> Lights are generated using grid system on large rooms larger than 12x12 room dimensions

- unity/Assets/Addressables/MCS/mcs_object_registry.json
Getting this out before sprint planning. I want to do a bit more testing but I think this is the only change that's needed. Once I finish sorting out some issues with my locally-built addressables, I'll update the integration tests accordingly.
When this branch is finalized, approved, and merged, we can simply cherry-pick this commit and merge it into `master` as well, to rebuild the main asset bundles and "release" the modified soccer ball.
> MCS-1253 Changed default drag of soccer ball.

- unity/Assets/Scripts/MCSMain.cs
Python PR: https://github.com/NextCenturyCorporation/MCS/pull/561
Summary (copied from Python PR):
A few months ago, when I was playing around with the moving target scenes, I encountered an issue in which the ball might bounce up a little when rolling at a fast speed across a supposedly smooth floor due to the way we're segmenting the floor in scenes containing lava. For reference, here's the Slack thread and a PR we merged with fixes:
- https://machinecommonsense.slack.com/archives/G01JFPF15R9/p1643925036628799
- https://github.com/NextCenturyCorporation/ai2thor/pull/199
While this worked in my initial testing, unfortunately, when you increase the room size, you need to increase the speed as well, and this issue reappears. It even happens if you eliminate all the `bounciness` from the …
> MCS-1295 Added partitionFloor option for MCS scene files. (Unity)

- unity/Assets/Scripts/MCSMain.cs
I noticed the far clipping plane was getting set somewhere to `9999`, which is much bigger than we'd ever need. I changed it back to its previous value (`150`, which allows you to see corner-to-corner across a 100x100 size room), and added a comment about why it's important. I also added a comment about the need to "reset" the camera (from Jacob's PR that he recently merged). Please let me know if you have any questions or concerns about the behavior.
> Fixed issue with super big far clipping plane.

- unity/Assets/Scripts/MCSSimulationAgent.cs
Currently, the skin on an agent's head remains light colored (the default), even when the skin on the rest of the body is set to a different color. This is because `facelessHead` is always non-null after initialization, even when the agent isn't "faceless" (the `facelessHead` is just inactive), so the `else` wasn't triggering. I don't believe this issue is critical enough on its own to demand a post-feature-freeze release.
> MCS-1320 Fixed a bug in which agent head skin color was never being properly set

- unity/Assets/Scripts/MCSMain.cs
Changed the hard-coded room dimensions for passive physics scenes so that the room is deeper in scenes with version >= 3. The room will remain the old size for scenes from Evals 2 - 4. I'll update the hypercube scene generator shortly to use this new version number in future passive physics scenes.
Updates to integration tests: https://github.com/NextCenturyCorporation/MCS/pull/573
> MCS-1333 Updated passive physics scene properties for Eval 5.

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/MCSController.cs
- unity/Assets/Scripts/MCSMain.cs
After testing different configurations, waiting two frames at the beginning is necessary for this to work. Keep in mind, this is not two physics steps but rather two unity update frames. I dont know how big of an issue this is but it was the only way I could get this to work for now. Without it the object would not spawn in in time for it to be detected. _Note_, even though the agent is looking at the object in the pictures, even if it was turned 180 degrees the raycasts still work and it will detect that it is visible
TOP OF THE OBJECT IS VISIBLE
NOT VISIBLE
> MCS-1341 Check if target is visible at start

- unity/Assets/Scripts/BaseFPSAgentController.cs
[MCS](https://github.com/NextCenturyCorporation/ai2thor/pull/251)
Sometimes when the performer was walking into a moving agent in my agent identification hypercube scenes, the agent would get stuck and be unable to move backward after colliding. 
To see what I mean, you can run the new integration test 148 on dev to see the performer get obstructed from moving left right or back when it clearly should be able to. Run that same test on this branch to see that the performer can move left, right, and back, when it is not obstructed by the agent in those directions.
> Performer stuck on moving agents
