NextCenturyCorporation/ai2thor

- README.md
- unity/Assets/Resources/MCS/Scenes/ball_close.json
- unity/Assets/Resources/MCS/Scenes/ball_far.json
- unity/Assets/Resources/MCS/Scenes/ball_obstructed.json
- unity/Assets/Resources/MCS/Scenes/playroom.json
- unity/Assets/Resources/MCS/ai2thor_object_registry.json
- unity/Assets/Resources/MCS/ai2thor_object_registry.json.meta
- unity/Assets/Resources/MCS/primitive_object_registry.json
- unity/Assets/Scenes/MCS.unity
- unity/Assets/Scripts/CanOpen_Object.cs
- unity/Assets/Scripts/DebugDiscreteAgentController.cs
- unity/Assets/Scripts/InstantiatePrefabTest.cs
- unity/Assets/Scripts/MachineCommonSenseController.cs
- unity/Assets/Scripts/MachineCommonSenseMain.cs
- unity/Assets/Scripts/MachineCommonSenseSceneManager.cs
- unity/Assets/Scripts/MachineCommonSenseSceneManager.cs.meta
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/PhysicsSceneManager.cs
- unity/Assets/Scripts/SimObjType.cs
Sorry, there ended up being a lot to this one review.  Please let me know if you have any questions.
Accomplishments:
- MCS-69: AI2-THOR objects can now be defined in the "ai2thor_object_registry" file and dynamically loaded into the MCS scene from its JSON config file.
- MCS-70: Fixed a bunch of the behavior related to picking up objects, placing them in/on "receptacles" (like boxes and tables), and interacting with receptacles (like opening and closing boxes or drawers).
- MCS-43: Added a bunch of new options for configuring objects in our JSON config files.
- MCS-11: Started a "sandbox" JSON config file (`playroom.json`).
Note that, the first time you checkout this branch and load it in the Unity Editor, it will take a little while to load because I had to copy a lot of AI2-THOR assets …
> MCS-69 MCS-70 Added AI2-THOR Objects and Fixed Behavior with Receptacles

- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/MachineCommonSenseController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Associated Python API changes here: https://github.com/NextCenturyCorporation/MCS/pull/11
(This was branched from MCS-69-code last week -- I'll resolve the conflict listed once I look at the open PR for that branch)
> MCS-58 & MCS-60 - Returning correct action status for PickupObject and DropObject

- README.md
- unity/Assets/Scripts/MachineCommonSenseController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Also added this + other action status related changes to the changelog.
Python API changes here: https://github.com/NextCenturyCorporation/MCS/pull/15
> Add return status codes for PutObject (MCS-59).

- unity/Assets/Scripts/MachineCommonSenseController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Python API changes here: https://github.com/NextCenturyCorporation/MCS/pull/18
> Adding return statuses for PushObject and PullObject (MCS-62, MCS-63).

- unity/Assets/Scripts/CanOpen_Object.cs
Fixed a bug in calculating the position/rotation/scale of opened and closed objects.
> MCS-64 MCS-65 Bug fix: opened and closed objects

- README.md
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Took lots of different trial and error, lots of testing, feel like I had to have missed something, let me know what I didn't think of.
> MCS-99: Initial design for moving partial if obstructed

- README.md
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Kept forgetting to open a PR for this.  Created a new ticket if we ever decide to make the object in hand visible.
> MCS-100:  Check if object in hand is visible, return true for rotation.

- README.md
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/MachineCommonSenseController.cs
Corresponding Python PR: https://github.com/NextCenturyCorporation/MCS/pull/106
> MCS-193 Added clipping planes to output metadata in Unity

- unity/Assets/Scripts/SimObjPhysics.cs
https://nextcentury.atlassian.net/browse/MCS-228
This solution might be way too simple, but tested the scene numerous times after doing this and everything appears fine.
> MCS-228 Fixed tag error on walls (wall_left should have SimObj tag)

- unity/Assets/Scripts/Contains.cs
https://nextcentury.atlassian.net/browse/MCS-226
> Mcs 226 (Added receptacle points that scale with collider size)

- unity/Assets/Scripts/MCSMain.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/SimObjPhysics.cs
Also fixes null pointer exception in case there are no visibility points set.
> Fix for a small cube not having visibility points.

- README.md
- unity/Assets/Scripts/CanOpen_Object.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Handling edge cases where an agent could still open a drawer so that they were inside of it.
> MCS-227 (take two)

- unity/Assets/Scripts/MCSMain.cs
Fixes the bug that Falk reported: https://machinecommonsense.slack.com/archives/CTR31V12M/p1604679024159400
> Fixed a z-fighting bug in the isometric agent scenes.

- unity/Assets/Resources/MCS/Custom/Prefabs/letter_l_narrow.prefab
- unity/Assets/Resources/MCS/Custom/Prefabs/letter_l_narrow.prefab.meta
- unity/Assets/Resources/MCS/Custom/Prefabs/letter_l_wide.prefab
- unity/Assets/Resources/MCS/Custom/Prefabs/letter_l_wide.prefab.meta
- unity/Assets/Resources/MCS/Scenes/primitives.json
- unity/Assets/Resources/MCS/mcs_object_registry.json
- unity/Assets/Resources/MCS/primitive_object_registry.json
- unity/Assets/Scripts/MCSController.cs
- unity/Assets/Scripts/MCSMain.cs
- Added triangles and L shapes.
- Added changeMaterials and togglePhysics JSON config properties.
> MCS-434 Gravity Support (Version 0.3.7)

- unity/Assets/Scripts/MCSController.cs
Fixes NextCenturyCorporation/MCS#230
> Fix bug that makes playroom hang

- README.md
- unity/Assets/Resources/MCS/primitive_object_registry.json
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/Contains.cs
- unity/Assets/Scripts/InstantiatePrefabTest.cs
- unity/Assets/Scripts/MCSConfig.cs
- unity/Assets/Scripts/MCSController.cs
- unity/Assets/Scripts/MCSMain.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/SimObjPhysics.cs
- unity/ProjectSettings/ProjectSettings.asset
Just all the commits since 0.3.7
> Finalizing 0.3.8

- unity/Assets/Resources/MCS/Scenes/large_room.json
- unity/Assets/Resources/MCS/Scenes/small_room.json
- unity/Assets/Scripts/MCSMain.cs
Adds ability to set room size in scene file.  Integration tests are in coming MCS pull request.
Many existing integration tests are failing, but were also failing prior to this work.
> Mcs 95 config room size

- README.md
Took a stab at this -- please let me know if anything is incorrect (particularly Linux users!)
> Updating readme instructions post-2.5 merge.

- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/MCSController.cs
- unity/Assets/Scripts/MCSMain.cs
Added code to adjust height of controller when moving off platforms.  Also, will adjust x,z of controller when falling off a platform such that it doesn't get stuck inside the platform.
> Updated platform handling code

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/DebugDiscreteAgentController.cs
- unity/Assets/Scripts/MCSController.cs
Associated Python API PR here: https://github.com/NextCenturyCorporation/MCS/pull/289
> MCS-540: Teleport within end habituation if needed

- README.md
- unity/Assets/Scenes/MCS.unity
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/MCSController.cs
Reduced skin width
Applied scale to determining valid movement
Fixed platform dropping adjustment code.
> Mcs 521 obstructed movement

- unity/Assets/Scripts/MCSController.cs
- unity/Assets/Scripts/MCSMain.cs
I also added relevant integration tests: https://github.com/NextCenturyCorporation/MCS/pull/294
> Don't automatically adjust the performer agent's height in passive scenes

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/MCSController.cs
Closes https://github.com/NextCenturyCorporation/MCS/issues/239
Associated Python API PR: https://github.com/NextCenturyCorporation/MCS/pull/299
> Add performer radius to metadata, rename reach property (MCS-441).

- README.md
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/MCSController.cs
- unity/Assets/Scripts/MCSMain.cs
Added frame rate to metadata.
Integration tests fail if run sequentially until https://github.com/NextCenturyCorporation/MCS/pull/281 is merged.
Associated pull request: https://github.com/NextCenturyCorporation/MCS/pull/308
> Mcs 512 return frame rate

- README.md
- unity/Assets/Scenes/MCS.unity
- unity/Assets/Scripts/BaseFPSAgentController.cs
This ticket seemed relatively simple, except we needed to push reach distance down to a goal for traversal rewards.
Associated ticket in other repo: https://github.com/NextCenturyCorporation/MCS/pull/318
> MCS-626 updated to move maxVisibleDistance to Unity code

- unity/Assets/Resources/MCS/Custom/Prefabs/letter_l_wide_tall.prefab
- unity/Assets/Resources/MCS/Custom/Prefabs/letter_l_wide_tall.prefab.meta
- unity/Assets/Resources/MCS/mcs_object_registry.json
- unity/Assets/Scripts/MCSMain.cs
- Added `letter_l_wide_tall` object
- Added the centerOfMass scene configuration file property to set an object's center of mass.
- Added the resetCenterOfMass scene configuration file property to reset an object's center of mass when it bounces off of the ground (when its Y velocity becomes positive).
> MCS-658 Center of Mass Scene File Property for Gravity Support Hypercubes

- unity/Assets/Scripts/SimObjPhysics.cs
This passed the integration tests
> Fixed Sub-object receptacle bounding box errors

- unity/Assets/Scripts/MCSController.cs
- unity/Assets/Scripts/MCSMain.cs
https://github.com/NextCenturyCorporation/MCS/pull/367 i had to make some integration test updates too but after the updates everything passed
> Removed Physics Substeps from MCS main and MCS controller

- unity/Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
- unity/Assets/Addressables/MCS/Scenes/floor_textures.json
- unity/Assets/Addressables/MCS/Scenes/floor_textures.json.meta
- unity/Assets/Addressables/MCS/Scenes/floor_textures_with_holes.json
- unity/Assets/Addressables/MCS/Scenes/floor_textures_with_holes.json.meta
- unity/Assets/Scenes/MCS.unity
- unity/Assets/Scripts/MCSMain.cs
This branches off of https://github.com/NextCenturyCorporation/ai2thor/pull/156
Tests: https://github.com/NextCenturyCorporation/MCS/pull/387
> Textures on specific areas of the floor

- unity/Assets/AddressableAssetsData/AddressableAssetSettings.asset
- unity/Assets/Resources/MCS.meta
- unity/Assets/Scripts/Addressables/Editor/AddressablesEditor.cs
- unity/Assets/Scripts/Addressables/Editor/JenkinsBuild.cs
profile points to ai2thor-mcs-addressables-dev
Set as active.
> Added Addressables development profile

- unity/Assets/Scripts/MCSMain.cs
Corresponding Python PR: https://github.com/NextCenturyCorporation/MCS/pull/411
Integration Test 089:
https://user-images.githubusercontent.com/10994382/134605597-12d196b8-d498-4cb5-833e-0528d2f9165c.mp4
Integration Test 090:
https://user-images.githubusercontent.com/10994382/134605604-7add74e6-0f07-411f-8b45-24654b053ef5.mp4
> MCS-820 Added support for configuring infinitely repeating intervals on many scripted actions in MCS scenes

- unity/Assets/Scripts/MCSMain.cs
Wait for Dean's approval before merging
> [Unity] Release 0.4.6

- unity/Assets/AddressableAssetsData/AssetGroups/Scenes.asset
- unity/Assets/Scenes/MCS.unity
- unity/Assets/Scripts/MCSController.cs
MCS --- https://github.com/NextCenturyCorporation/MCS/pull/457
> Seesaw works with pass, rotation, and other actions

- unity/Assets/Scripts/MCSController.cs
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/466)
Now objects are held at: **distance of the largest bounding box size + agent's radius + small buffer distance** units away
> Fixed holding object code so throwing and dropping work consistently

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/MCSController.cs
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/474)
> Track total steps on lava

- README.md
- unity/Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
- unity/Assets/Addressables/MCS/Scenes/platform_lips.json
- unity/Assets/Addressables/MCS/Scenes/platform_lips.json.meta
- unity/Assets/Scenes/MCS.unity
- unity/Assets/Scripts/MCSMain.cs
- unity/Assets/Scripts/StructureObject.cs
[Scene Generator ](https://github.com/NextCenturyCorporation/mcs-private/pull/127/)
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/478)
> Platform lips

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/CanOpen_Object.cs
- unity/Assets/Scripts/MCSMain.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/SimObjPhysics.cs
Corresponding PRs:
[ILE](https://github.com/NextCenturyCorporation/mcs-private/pull/137)
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/495)
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/197)
> adding function to have a locked container

- unity/Assets/Addressables/MCS/Custom/Prefabs/Door4.prefab
Changed the door so it opens 180 degrees, but also sits on a wall 0.1 think. This prevents issues with the door blocking the robot's movement.
OLD:
https://user-images.githubusercontent.com/10994382/153430959-fef1b827-318d-43f4-92c5-99267537ed90.mp4
NEW:
https://user-images.githubusercontent.com/10994382/153430592-82cf6800-9e02-40c4-bcf6-bbbaa22d1125.mp4
> MCS-1139 Changed door object to open completely.

- unity/Assets/Scripts/MCSController.cs
- unity/Assets/Scripts/MCSMain.cs
Passive scenes are currently broken because the camera's height is being modified. This PR fixes the issue.
> MCS-1171 Fixed the viewpoint for passive scenes.

- unity/Assets/Scripts/MCSMain.cs
- unity/Assets/Scripts/SimObjPhysics.cs
- unity/ProjectSettings/DynamicsManager.asset
Corresponding Python PR: https://github.com/NextCenturyCorporation/MCS/pull/498
> MCS-1158 MCS-1160 Updates to support moving target scenes.

- unity/Assets/Scripts/DebugDiscreteAgentController.cs
- unity/Assets/Scripts/SimObjPhysics.cs
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/501)
> Push pull use ForceMode.Impulse

- unity/Assets/Scripts/MCSMain.cs
- unity/Assets/Scripts/StructureObject.cs
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/204)
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/507)
[ILE](https://github.com/NextCenturyCorporation/mcs-private/pull/142)
> Mcs 1176 add lips to ramp platforms

- README.md
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/CanOpen_Object.cs
- unity/Assets/Scripts/MCSController.cs
- unity/Assets/Scripts/MCSMain.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Python API: https://github.com/NextCenturyCorporation/MCS/pull/519
ILE: https://github.com/NextCenturyCorporation/mcs-private/pull/147
If restrictOpenDoors is true, only allow one open door at a time (making sure to still allow other types of openable objects to be opened).
> MCS-1140 - restrict open doors

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/MCSController.cs
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/535)
I changed lava steps to private too since I was adding new variables under it and noticed that it is not referenced in other scripts
> Object IDs from image coordinates output metadata

- unity/Assets/Addressables/MCS/Scenes/agents_movement.json
- unity/Assets/Addressables/MCS/Scenes/agents_movement.json.meta
- unity/Assets/Scripts/MCSController.cs
- unity/Assets/Scripts/MCSMain.cs
- unity/Assets/Scripts/MCSSimulationAgent.cs
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/552)
There are a lot of comments in this code because I needed them to keep track of the different conditions. I also serialized a lot of private variables so I could see them in the inspector as I found those very useful. I can remove both of these but I think they are helpful.
> Simulation Agent Movement

- unity/Assets/Addressables/MCS/Scenes/agents_obstructed.json
- unity/Assets/Addressables/MCS/Scenes/agents_obstructed.json.meta
- unity/Assets/Scripts/MCSSimulationAgent.cs
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/553)
> Agent movement blocked

- unity/Assets/Scripts/SimObjPhysics.cs
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/562)
> Fixed rotation and movement actions so that the object is obstructed by performer

- unity/Assets/Scripts/MCSSimulationAgent.cs
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/563)
> Agent movement with identical endpoints fixed

- unity/Assets/Scripts/MCSMain.cs
I wish I had an explanation for why this works but after messing around with every available lighting setting with the scene lights, scene settings, and project graphical/quality settings, this was the only thing that did the job.
[Please use this json to see the change](https://nextcentury.atlassian.net/browse/MCS-1309?atlOrigin=eyJpIjoiMDA2ODU4YTRhNTliNDVlOWIzZWVmODdjMWNhMTY0NzIiLCJwIjoiaiJ9)
**Before Image:**
**After Image:**
> Fixed rendering bug

- unity/Assets/Scripts/MCSSimulationAgent.cs
- unity/Assets/Scripts/MCSSimulationAgent.cs.meta
[Private](https://github.com/NextCenturyCorporation/mcs-private/pull/236)
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/574)
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/246)
This try catch here was the only way I could get these new animations to work. I created these by copying the first frame of the idle poses and letting them play for 5 seconds by default. If isLoopAnimation is true they will be frozen indefinitely. The new animations are:
```
TPE_freeze
TPF_freeze
TPM_freeze
```
> Agent freezing
